### ISSUE TITLE
Error: Cannot find module 'cosmicjs'

### ISSUE THREAD

**Issue by tekhaus** [cosmicjs/gatsby-source-cosmic#12]
I received a build error on a brand new generic Gatsby v5 site, with only the latest Cosmic source plugin added.

```
Require stack:
  - /my-gatsby-site/node_modules/@cosmicjs/gatsby-source-cosmic/dist/helpers/
  **fetchObjects.js**
```

When I downloaded the plugin source, built it locally, and used it with resolve in gatsby-config.js, then it worked just fine.

It looks like one or more files in the published v2 dist didn't get the new sdk and instead are referencing the old cosmicjs.

![image](https://github.com/cosmicjs/gatsby-source-cosmic/assets/1009347/9e9677c1-0bc7-43bf-929c-50d41bc4d2d1)

**Comment by tonyspiro** [comment]
Closing this as we have resolved this in the latest (v2.0.2).

**Comment by tekhaus** [comment]
Thank you! I just patched my build with v2.0.2 and all is well 👍

**Comment by tonyspiro** [comment]
Great to hear.  Thank you for the report! 🙌🏻
